name: googlemap_testapp
description: A new Flutter project.

publish_to: 'none' 

version: 3.1.0

environment:
  sdk: '>=2.19.1 <3.0.0'
  flutter: ">=3.3.0"

dependencies:
  async: ^2.9.0
  collection: ^1.16.0
  custom_info_window: ^1.0.1
  flutter:
    sdk: flutter
  flutter_map: ^3.1.0
  http: ^0.13.5
  google_maps_flutter: ^2.3.1
  latlong2: ^0.8.0
  meta: ^1.8.0
  polylabel: ^1.0.1
  positioned_tap_detector_2: ^1.0.4
  proj4dart: ^2.1.0
  tuple: ^2.0.0
  vector_math: ^2.1.2
  flutter_speed_dial: ^3.0.5
  google_fonts: ^4.0.3
  provider: ^6.0.5
  dio: ^5.0.1
  shared_preferences: ^2.0.18
  flutter_secure_storage: ^8.0.0
  device_info_plus: ^8.1.0
  liquid_swipe: ^3.0.0
  smooth_page_indicator: ^1.0.1
  lottie: ^2.2.0
  permission_handler: ^10.2.0 
  location: ^4.4.0

  
  

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - images/strawberry.jpeg
    - images/dost.png
    - images/
    - assets/images/splash_images/
    - assets/images/
